services:
  userandunitmanagement.api:
    image: ${DOCKER_REGISTRY-}userandunitmanagementapi
    build:
      context: .
      dockerfile: UserAndUnitManagement.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=localhost;Database=UserAndUnitManagementDb;User Id=sa;Password=yourStrong(!)Password;MultipleActiveResultSets=true;TrustServerCertificate=True"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: 'yourStrong(!)Password'
      ACCEPT_EULA: 'Y'
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "yourStrong(!)Password", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s