networks:
  internal_network:
    driver: bridge

services:
  communityconnect-userandunitmgmtapi-dev:
    image: ${DOCKER_REGISTRY-}communityconnect-userandunitmgmtapi
    build:
      context: UserAndUnitManagement
      dockerfile: UserAndUnitManagement.Api/CommunityConnect.UserAndUnitMgmtAPI.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
      - "ConnectionStrings:DefaultConnection=Server=communityconnect-db-dev;Database=UserAndUnitManagementDb;User Id=sa;Password=5Tmb-_zJryCV)yLv)NNw;MultipleActiveResultSets=true;TrustServerCertificate=True"
    volumes:
      - .:/src
    depends_on:
      communityconnect-db-dev:
        condition: service_healthy
    profiles: ["development"]
    entrypoint: ["dotnet", "CommunityConnect.UserAndUnitMgmtAPI.dll"]
    command: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - internal_network

  communityconnect-gateway-dev:
    image: ${DOCKER_REGISTRY-}communityconnect-gateway
    build:
      context: Gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      communityconnect-userandunitmgmtapi-dev:
        condition: service_healthy
    profiles: ["development"]
    networks:
      - internal_network

  communityconnect-db-dev:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: '5Tmb-_zJryCV)yLv)NNw'
      ACCEPT_EULA: 'Y'
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "5Tmb-_zJryCV)yLv)NNw", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    profiles: ["development"]
    networks:
      - internal_network
